rule_files:
- '*.rules'
scrape_configs:
- job_name: worker-metrics
  scrape_interval: 10s
  kubernetes_sd_configs:
    - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace]
    action: keep
    regex: micado-worker
  metric_relabel_configs:
  - source_labels: [container_label_io_kubernetes_pod_namespace]
    regex: .*-system
    action: drop
  - source_labels: [container_label_io_kubernetes_pod_namespace]
    regex: micado-worker
    action: drop

- job_name: kube-services
  scrape_interval: 10s
  kubernetes_sd_configs:
    - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace]
    action: drop
    regex: .*-system
  - source_labels: [__meta_kubernetes_namespace]
    action: drop
    regex: micado-worker
  - source_labels: [__meta_kubernetes_service_label_component]
    action: drop
    regex: apiserver
  - source_labels: [__address__]
    target_label: instance

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093