---
- name: 'K8s: Turn off swap'
  shell: swapoff -a

- name: 'K8s: Add APT key'
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: 'K8s: Add APT repository'
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    filename: 'kubernetes'

- name: 'K8s: Install APT packages'
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: 'Docker: prevent package from being upgraded'
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: 'K8s: CNI plugin fix'
  shell: sysctl net.bridge.bridge-nf-call-iptables=1

- name: 'K8s: Initialization'
  shell: docker swarm init
        --apiserver-advertise-address={{ ansible_default_ipv4.address }}
        --pod-network-cidr=10.244.0.0/16

- name: 'K8s: Create .kube dir'
  become: yes
  become_user: ubuntu
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: 'K8s: cp admin.conf to .kube/config'
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: yes
    owner: ubuntu

- name: 'K8s: Get worker token'
  shell: kubeadm token create --print-join-command
  register: worker_token_raw

- name: 'K8s: Set join command'
  set_fact:
    worker_token: "{{ worker_token_raw.stdout_lines[0] }}"

- name: 'K8s: Install Flannel pod network'
  become: yes
  become_user: ubuntu
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
