---
- include: setup-master-node.yml

- include: docker-install.yml

- include: k8s-install.yml
  when: container_orchestrator == 'k8s'

- include: swarm-init.yml
  when: container_orchestrator == 'swarm'

- include: files.yml

- include: worker_node.yml

- include: docker-pull-images.yml

- include: start_micado.yml

- include: docker-login.yml
  when: container_orchestrator == 'swarm' and docker_cred_path is defined
