---
- include: setup-master-node.yml

- name: Load the credentials and security settings from the playbook
  include_vars:
    file: "credentials.yml"
    name: config

- include: docker-install.yml

- include: files.yml

- include: worker_node.yml

- include: docker-pull-images.yml

- include: start_micado.yml

- include: docker-login.yml

- name: Enable packet filtering
  shell: systemctl enable --now iptables
