---
- name: 'Docker Swarm: check membership'
  shell: docker node ls
  register: swarmmember
  changed_when: swarmmember.rc == 1
  failed_when: swarmmember.rc not in [0,1]

- name: 'Docker Swarm: Initialization'
  shell: docker swarm init
        --listen-addr {{ ansible_default_ipv4.address }}
        --advertise-addr {{ ansible_default_ipv4.address }}
        --availability drain
  when: swarmmember.rc == 1

- name: 'Docker Swarm: Get worker token'
  shell: docker swarm join-token -q worker
  register: worker_token
