global:
    
# The root route on which each incoming alert enters.
# The root route with all parameters, which are inherited by the child
# routes if they are not overwritten.
route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 20s
  repeat_interval: 5m
  group_by: [alertname]

  routes:
  - receiver: 'default'
    match:
      type: docker
    group_wait: 10s
    group_interval: 20s
    repeat_interval: 1m
    group_by: [alertname]

