version: '3.3'
services:
  stressng:
    image: lorel/docker-stress-ng
    deploy:
      resources:
        reservations:
          cpus: '1.0'
    command: [ "--cpu", "0", "--cpu-method", "pi", "-l", "85" ]
       

