---
- name: 'Occopus Credentials: Load the credentials from the playbook'
  include_vars:
    file: "{{ cloud_cred_path }}"
    name: config

- name: 'Security Credentials: Load the credentials and security settings from the playbook'
  include_vars:
    file: "{{ micado_cred_path  }}"
    name: security

- name: Copy config templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - { src: 'user_data/auth_data_credential_manager.csv.j2', dest: '/var/lib/micado/credman/config/provisioning.csv'}
    - { src: 'user_data/user_data_zorp.env.j2', dest: '/var/lib/micado/zorp/config/user_data_zorp.env'}
    - { src: 'micado/micado-manifest.yml.j2', dest: '/var/lib/micado/micado-manifest.yml'}
    - { src: 'iptables/iptables.conf.j2', dest: '/etc/iptables.conf'}
    - { src: 'iptables/ip6tables.conf.j2', dest: '/etc/ip6tables.conf'}
    - { src: 'user_data/auth_data.yaml.j2', dest: '/var/lib/micado/occopus/data/auth_data.yaml'}
    - { src: 'worker_node/cloud_init_worker.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/cloud_init_worker.yaml'}
    - { src: 'worker_node/temp_infrastructure_descriptor.yaml.j2', dest: '/var/lib/micado/toscasubmitter/system/infrastructure_descriptor.yaml'}
    - { src: 'ipsec/ipsec.conf', dest: '/etc/ipsec.conf'}

- name: 'Worker node: Disable Unattended Upgrades'
  lineinfile:
    path: /var/lib/micado/toscasubmitter/system/cloud_init_worker.yaml
    insertafter: '^runcmd:'
    line: '  - sed -i ''s/APT::Periodic::Unattended-Upgrade "1";/APT::Periodic::Unattended-Upgrade "0";/g'' /etc/apt/apt.conf.d/20auto-upgrades'
  when: disable_worker_updates is defined and disable_worker_updates
